server:
  port: 8080

spring:
  datasource:
    username: root
    password: pass
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jsoup:
  connection:
    userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
    referrer: http://www.google.com

indexing-settings:
  sites:
#    - url: https://www.lenta1256.ru
#      name: Лента1256
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
#    - url: https://et-cetera.ru/mobile/
#      name: et-cetera
    - url: https://www.svetlovka.ru/
      name: svetlovka
    - url: https://dombulgakova.ru
      name: dombulgakova
