server:
  port: 8080

spring:
  datasource:
    username: root
    password: pass
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

jsoup:
  connection:
    userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
    referrer: http://www.google.com

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "error"
    searchengine: "DEBUG"
  file:
    name: appLog.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console:  "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"



indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.lenta123.ru
      name: Лента123.ру
#    - url: https://www.playback.ru
#      name: PlayBack
    - url: https://et-cetera.ru/mobile/
      name: Сetera-mobile
#    - url: https://ipfran.ru
#      name: ipfran
#    - url: https://nikoartgallery.com
#      name: nikoartgallery
